package jm.task.core.jdbc.dao;

public final class SQLQuery {
    public static final String CREATE_TABLE = "CREATE TABLE IF NOT EXISTS users (" +
                                                    "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                                                    "name VARCHAR(255), " +
                                                    "lastName VARCHAR(255), " +
                                                    "age SMALLINT)";
    public static final String DROP_TABLE = "DROP TABLE IF EXISTS users CASCADE";
    public static final String SELECT_ALL = "SELECT * FROM ";
    public static final String SELECT_COUNT = "SELECT COUNT(id) FROM";
    public static final String INSERT = "INSERT INTO users (name, lastName, age) VALUES (?, ?, ?)";
    public static final String DELETE = "DELETE FROM users WHERE id = ?";
    public static final String UPDATE = "UPDATE users SET ";
    public static final String CLEAR_TABLE = "TRUNCATE TABLE users RESTART IDENTITY";
}
