package jm.task.core.jdbc.dao;

import jm.task.core.jdbc.model.User;
import jm.task.core.jdbc.util.Util;
import org.hibernate.annotations.common.util.impl.LoggerFactory;
import org.jboss.logging.Logger;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

public class UserDaoJDBCImpl implements UserDao {

    private static final Logger log = LoggerFactory.logger(UserDaoJDBCImpl.class);

    public UserDaoJDBCImpl() { }

    private boolean checkTable(Connection connection,  String tableName) throws SQLException {
        DatabaseMetaData metaData = connection.getMetaData();
        try (ResultSet resultSet = metaData.getTables(null, "public", tableName, null)) {
            return resultSet.next();
        }
    }

    public void createUsersTable() {
        String sqlCreateTable = """
                CREATE TABLE IF NOT EXISTS users (
                    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR(255),
                    lastName VARCHAR(255),
                    age SMALLINT
                )
                """;
        try (Connection con = Util.getConnection();
             PreparedStatement stm = con.prepareStatement(sqlCreateTable)) {
            if (!checkTable(con, "users")) {
                stm.execute();
                log.info("Таблица users успешно создана...");
            } else log.warn("Таблица users уже есть...");
        } catch (SQLException s) {
            throw new RuntimeException(s);
        }
    }

    public void dropUsersTable() {
        String sqlDropTable = """
                DROP TABLE users CASCADE
                """;
        try (Connection con = Util.getConnection();
             PreparedStatement stm = con.prepareStatement(sqlDropTable)) {
            if (checkTable(con, "users")) {
                stm.execute();
                log.info("Таблица users успешно удалена...");
            } else log.warn("Удалить таблицу users невозможно, так как ее нету...");
        } catch (SQLException s) {
            throw new RuntimeException(s);
        }
    }

    public void saveUser(String name, String lastName, byte age) {
        String sqlInsertUser = """
                INSERT INTO users (name, lastName, age) VALUES (?, ?, ?)
                """;
        try (Connection con = Util.getConnection();
             PreparedStatement stm = con.prepareStatement(sqlInsertUser)) {
            if (checkTable(con, "users")) {
                stm.setString(1, name);
                stm.setString(2, lastName);
                stm.setByte(3, age);
                stm.executeUpdate();
                log.info("Успешно добавлена запись: " + name);
            } else log.warn("Невозможно добавить запись, так как нету таблицы users...");
        } catch (SQLException s) {
            throw new RuntimeException(s);
        }
    }

    public void removeUserById(long id) {
        String sqlDeleteUser = """
                DELETE FROM users WHERE id = ?
                """;
        try (Connection con = Util.getConnection();
             PreparedStatement stm = con.prepareStatement(sqlDeleteUser)) {
            if (checkTable(con, "users")) {
                stm.setLong(1, id);
                if (stm.executeUpdate() > 0) {
                    log.info("Запись успешно удаоена: <id = " + id + ">");
                } else log.warn("Невозможно удвлить запись, так как нету в таблице users запись с <id = " + id + ">");
            } else log.warn("Невозможно удвлить запись, так как нету таблицы users...");
        } catch (SQLException s) {
            throw new RuntimeException(s);
        }
    }

    public List<User> getAllUsers() {
        List<User> users = new ArrayList<>();
        String sqlAllUsers = """
                SELECT id, name, lastName, age FROM users
                """;
        try (Connection con = Util.getConnection();
             PreparedStatement stm = con.prepareStatement(sqlAllUsers)) {
            ResultSet result = stm.executeQuery();
            while (result.next()) {
                User usr = new User();
                usr.setId(result.getLong("id"));
                usr.setName(result.getString("name"));
                usr.setLastName(result.getString("lastName"));
                usr.setAge(result.getByte("age"));
                users.add(usr);
            }
        } catch (SQLException s) {
            throw new RuntimeException(s);
        }
        return users;
    }

    public void cleanUsersTable() {
        String sqlClearTableRecord = """
                TRUNCATE TABLE users RESTART IDENTITY
                """;
        try (Connection con = Util.getConnection();
             PreparedStatement stm = con.prepareStatement(sqlClearTableRecord)) {
            stm.executeUpdate();
            log.info("Все записи с таблицы users удалены и счетчик сброшен...");
        } catch (SQLException s) {
            throw new RuntimeException(s);
        }
    }
}
