package jm.task.core.jdbc.dao;

import jm.task.core.jdbc.model.User;
import jm.task.core.jdbc.util.Util;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.annotations.common.util.impl.LoggerFactory;
import org.jboss.logging.Logger;

import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.util.List;

public class UserDaoHibernateImpl implements UserDao {
    private static final Logger log = LoggerFactory.logger(UserDaoHibernateImpl.class);

    public UserDaoHibernateImpl() { }

    private boolean checkTable(SessionFactory sessionFactory, String tName) {
        try (Session session = sessionFactory.openSession()) {
            session.doReturningWork(connection -> {
                DatabaseMetaData mData = connection.getMetaData();
                try (ResultSet result = mData.getTables(null, "public", tName, null)) {
                    return result.next();
                }
            });
        } catch (Exception e) {
           log.error("Ошибка при проверке существования таблицы " + tName, e);
        }
        return false;
    }

    @Override
    public void createUsersTable() {
        /*String sqlCreateTable = """
                CREATE TABLE IF NOT EXISTS users (
                    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR(255),
                    lastName VARCHAR(255),
                    age SMALLINT
                )
                """;
        SessionFactory sessionFactory = Util.getSessionFactory();
        if (!checkTable(sessionFactory, "users")) {

            try (Session session = sessionFactory.openSession()) {
                session.beginTransaction();

            }

        } else
            log.warn("Таблицы users уже существует в БД.");*/
    }

    @Override
    public void dropUsersTable() {

    }

    @Override
    public void saveUser(String name, String lastName, byte age) {

    }

    @Override
    public void removeUserById(long id) {

    }

    @Override
    public List<User> getAllUsers() {
        return null;
    }

    @Override
    public void cleanUsersTable() {

    }
}
